#ifndef TUSB_CONFIG_H
#define TUSB_CONFIG_H

#define CFG_TUSB_MCU OPT_MCU_NONE
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUSB_RHPORT0_MODE OPT_MODE_HOST
#define CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))

#define CFG_TUH_DEVICE_MAX 4
#define CFG_TUH_ENUMERATION_BUFSIZE 256

#define CFG_TUH_CDC 1
#define CFG_TUH_NET 1
#define CFG_TUH_MSC 0
#define CFG_TUH_HID 0

#endif // TUSB_CONFIG_H